
from ingredient_parser.en import parse

print(parse('2 liters of milk'))
print(parse('2 lbs milk'))
print(parse('1 lbs milk'))
print(parse('1 lb milk'))
print(parse('1 pound milk'))
print(parse('1 # milk'))
print(parse('1 t milk.'))
print(parse('1 T milk.'))
print(parse('thirteen T milk'))
print("")
print(parse("1 bunch celery, cleaned and cut into 4 inch pieces"))
print("")
print(parse("4 teaspoons of Keith"))
print("")
print("")
print(parse("2 (8 ounce) packages cream cheese, softened"))
print(parse("2 8 ounce packages cream cheese, softened"))
print(parse("1 1/2 cups shredded Cheddar cheese"))
print(parse("1 cups shredded Cheddar cheese"))
print(parse("6 frozen skinless, boneless chicken breast halves"))