from ing_parser import parse

print(parse('2 liters of milk'))
print(parse('2 lbs milk'))
print(parse('1 lbs milk'))
print(parse('1 lb milk'))
print(parse('1 pound milk'))
print(parse('1 # milk'))
print(parse('1 t milk.'))
print(parse('1 T milk.'))
print(parse('thirteen T milk'))
print("")
print(parse("1 bunch celery, cleaned and cut into 4 inch pieces"))
print("")
print(parse("4 teaspoons of Keith"))
print("")
print("")
print(parse("2 (8 ounce) packages cream cheese, softened"))
print(parse("2 8 ounce packages cream cheese, softened"))
print(parse("1 1/2 cups shredded Cheddar cheese"))
print(parse("1 cups shredded Cheddar cheese"))

print(parse("1 pound skinless, boneless chicken breast halves - cubed"))
# error
print(parse("1 cup sliced carrotsprint"))
print(parse("1 cup frozen green peas"))
print(parse("1/2 cup sliced celery"))

print(parse("1/3 cup butter"))
print(parse("1/3 cup chopped onion"))
print(parse("1/3 cup all-purpose flour"))
print(parse("1/2 teaspoon salt"))
print(parse("1/4 teaspoon black pepper"))
print(parse("1/4 teaspoon celery seed"))
print(parse("1 3/4 cups chicken broth"))
print(parse("2/3 cup milk"))
print(parse("2 (9 inch) unbaked pie crusts"))
print(parse("2 9 inch unbaked pie crusts"))
print(parse(".9 inch unbaked pie crusts"))
print(parse("0.9 inch unbaked pie crusts"))

print(parse("6 frozen skinless, boneless chicken breast halves"))
print(parse("1 gal. of peanuts"))
print(parse("salt and ground black pepper to taste"))
print(parse("1 (10.75 ounce) can condensed Cheddar cheese soup"))
print(parse("1 10.75 ounce can condensed Cheddar cheese soup"))
print(parse("200 cans of condensed Cheddar cheese soup"))